[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { path = "../../../aya/aya", features = ["async_tokio"] , optional = true}
aya-bpf = { git = "https://github.com/aya-rs/aya" }

[lib]
path = "src/lib.rs"
